<a href="https://colab.research.google.com/github/plus2net/numpy/blob/main/numpy_12_advanced_array_creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://www.plus2net.com/images/top2.jpg)        Read more on [Advanced Array Creation ](https://www.plus2net.com/python/numpy-advanced-array-creation.php) | [ Numpy ](https://www.plus2net.com/python/numpy.php)

In [1]:
import numpy as np

x = np.array([1,2,3])
y = np.array([10,20,30])

X, Y = np.meshgrid(x, y)
print(X)
# [[1 2 3]
#  [1 2 3]
#  [1 2 3]]

print(Y)
# [[10 10 10]
#  [20 20 20]
#  [30 30 30]]

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[10 10 10]
 [20 20 20]
 [30 30 30]]


In [2]:
a = np.array([1,2,3,4])
print(np.diag(a))
# [[1 0 0 0]
#  [0 2 0 0]
#  [0 0 3 0]
#  [0 0 0 4]]

M = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.diag(M))   # [1 5 9] extract diagonal

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1 5 9]


In [3]:
v = np.array([1,2,3])
print(np.tile(v, 3))
# [1 2 3 1 2 3 1 2 3]

M = np.array([[1,2],[3,4]])
print(np.tile(M, (2,3)))
# [[1 2 1 2 1 2]
#  [3 4 3 4 3 4]
#  [1 2 1 2 1 2]
#  [3 4 3 4 3 4]]

[1 2 3 1 2 3 1 2 3]
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [4]:
x = np.array([1,2,3])
print(np.repeat(x, 2))
# [1 1 2 2 3 3]

M = np.array([[1,2],[3,4]])
print(np.repeat(M, 2, axis=0))
# [[1 2]
#  [1 2]
#  [3 4]
#  [3 4]]

[1 1 2 2 3 3]
[[1 2]
 [1 2]
 [3 4]
 [3 4]]


In [5]:
x = np.array([0, 1, 2])
y = np.array([0, 10, 20, 30])

X, Y = np.meshgrid(x, y)

print("X grid:")
print(X)

print("\nY grid:")
print(Y)

X grid:
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]

Y grid:
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [6]:
import numpy as np
# Create a grid of (x,y) points for x=[0,1,2] and y=[0,10,20,30].
# Create a sample 4x4 matrix
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

print("Original matrix:")
print(M)

# Extract diagonal elements
diagonal_elements = np.diag(M)
print("\nDiagonal elements:")
print(diagonal_elements)

# Create a copy of the matrix to modify
M_modified = M.copy()

# Replace diagonal elements with zeros
np.fill_diagonal(M_modified, 0)

print("\nMatrix with diagonal elements replaced by zeros:")
print(M_modified)

Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Diagonal elements:
[ 1  6 11 16]

Matrix with diagonal elements replaced by zeros:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [11]:
# Tile [1,0] five times to create a 1D pattern.
import numpy as np

v = np.array([1, 0])
tiled_array = np.tile(v, 5)
print(tiled_array)

[1 0 1 0 1 0 1 0 1 0]


In [10]:
# Repeat each row of [[5,6],[7,8]] three times.
import numpy as np

M = np.array([[5, 6], [7, 8]])
repeated_array = np.repeat(M, 3, axis=0)
print(repeated_array)

[[5 6]
 [5 6]
 [5 6]
 [7 8]
 [7 8]
 [7 8]]
