<a href="https://colab.research.google.com/github/plus2net/numpy/blob/main/numpy_17_ufuncs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://www.plus2net.com/images/top2.jpg)        Read more on [ufuncs  ](https://www.plus2net.com/python/numpy-ufuncs.php) | [ Numpy ](https://www.plus2net.com/python/numpy.php)

In [3]:
import numpy as np

x = np.array([1., 4., 9.])
print(np.sqrt(x))              # elementwise sqrt; <class 'numpy.ufunc'>

a = np.array([1,2,3], dtype=np.float64)
b = np.array([10,20,30], dtype=np.float64)
np.add(a, b)            # same as a + b (binary ufunc)

[1. 2. 3.]


array([11., 22., 33.])

In [5]:
M = np.array([[1,2,3],[4,5,6]], dtype=np.float64)  # (2,3)
v = np.array([10,20,30], dtype=np.float64)          # (3,)
print(np.add(M, v))       # v broadcasts across rows
print(np.multiply(M, 2))  # scalar broadcast

[[11. 22. 33.]
 [14. 25. 36.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [9]:
x = np.array([1,2,3,4], dtype=np.int64)

print(np.add.reduce(x))         # 10
print(np.multiply.reduce(x))    # 24

print(np.add.accumulate(x))     # [1, 3, 6, 10]
np.multiply.accumulate(x)# [1, 2, 6, 24]

np.multiply.outer([1,2,3],[10,20])  # 3x2 table

10
24
[ 1  3  6 10]


array([[10, 20],
       [20, 40],
       [30, 60]])