<a href="https://colab.research.google.com/github/plus2net/numpy/blob/main/numpy_13_axis_reduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://www.plus2net.com/images/top2.jpg)        Read more on [Axis Reduction ](https://www.plus2net.com/python/numpy-axis-reduction.php) | [ Numpy ](https://www.plus2net.com/python/numpy.php)

In [1]:
import numpy as np

X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])   # shape (3,3)

print(X.sum(axis=0))  # [12 15 18]  column sums
print(X.sum(axis=1))  # [ 6 15 24]  row sums
print(X.sum())        # 45          all elements

[12 15 18]
[ 6 15 24]
45


In [2]:
mu_rows = X.mean(axis=1, keepdims=True)  # shape (3,1)
X_centered_by_row = X - mu_rows          # broadcasts to (3,3)

mu_cols = X.mean(axis=0, keepdims=True)  # shape (1,3)
X_centered_by_col = X - mu_cols

In [3]:
A = np.arange(12).reshape(3,4)

print(A.sum(axis=0))     # column sums
print(A.mean(axis=1))    # row means
print(A.min(axis=0))     # column minima
print(A.max(axis=1))     # row maxima
print(A.std(axis=0))     # column std dev
print(A.prod(axis=1))    # row product

[12 15 18 21]
[1.5 5.5 9.5]
[0 1 2 3]
[ 3  7 11]
[3.26598632 3.26598632 3.26598632 3.26598632]
[   0  840 7920]


In [4]:
idx = A.argmax(axis=1)          # index of max in each row
row_ids = np.arange(A.shape[0])
row_max_vals = A[row_ids, idx]  # values at those indexes
print(idx, row_max_vals)

[3 3 3] [ 3  7 11]


In [5]:
B = (A % 2 == 0)    # even mask
print(B.any(axis=1))   # any even per row
print(B.all(axis=1))   # all even per row?

[ True  True  True]
[False False False]


In [6]:
print(A.cumsum(axis=0))  # cumulative column sums
print(A.cumsum(axis=1))  # cumulative row sums

[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [7]:
T = np.arange(2*3*4).reshape(2,3,4)  # (depth=2, rows=3, cols=4)
print(T.mean(axis=0).shape)  # (3,4)  mean across depth
print(T.sum(axis=2).shape)   # (2,3)  sum across last axis

(3, 4)
(2, 3)


In [8]:
# 1) Standardize columns (Z-score)
X = np.random.randn(5, 3)
mu = X.mean(axis=0, keepdims=True)
sd = X.std(axis=0, keepdims=True)
Z = (X - mu) / sd

# 2) Find the column with max total
col_sums = X.sum(axis=0)
best_col = col_sums.argmax()

# 3) Normalize each row to sum to 1 (avoid div-by-zero)
row_sum = X.sum(axis=1, keepdims=True)
row_sum[row_sum == 0] = 1
X_norm = X / row_sum

In [9]:
# a) Given M=(6,4), subtract row-wise medians using keepdims
M = np.arange(24).reshape(6,4)
med = np.median(M, axis=1, keepdims=True)
print(M - med)

# b) From a (3,5) array, return the index of the max per column and the values
A = np.random.randint(0, 100, (3,5))
idx = A.argmax(axis=0)
vals = A[idx, np.arange(A.shape[1])]
print(idx, vals)

# c) For a (2,3,4) tensor, compute cumulative sums along the last axis
T = np.arange(24).reshape(2,3,4)
print(np.cumsum(T, axis=2))

[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]
[1 2 2 0 1] [81 98 92 95 79]
[[[ 0  1  3  6]
  [ 4  9 15 22]
  [ 8 17 27 38]]

 [[12 25 39 54]
  [16 33 51 70]
  [20 41 63 86]]]
