<p align="center"><a href="https://www.plus2net.com/python/numpy-eye.php"><img src="https://www.plus2net.com/images/top2.jpg" width="300" alt="plus2net Python Tutorials"></a></p>

# NumPy eye(): Identity Matrices, Shifted Diagonals and Masks

[Read the tutorial](https://www.plus2net.com/python/numpy-eye.php)

Run cells in order. All examples use synthetic embedded data. Save a copy in Drive before editing. Try the exercise before reading its solution.

## Create a Square Identity Matrix

With <code>M=None</code> and <code>k=0</code>, eye creates a square identity matrix. The default dtype is floating point. Its diagonal entries are one and all other entries are zero.

In [ ]:
import numpy as np
my_data = np.eye(3)
print(my_data)
print("Shape:", my_data.shape, "Dimensions:", my_data.ndim)
np.testing.assert_array_equal(my_data.diagonal(), [1, 1, 1])
assert my_data.shape == (3, 3)

**Expected output**

```text
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape: (3, 3) Dimensions: 2
```

## Choose Rows and Columns with N and M

N is the row count; M is the column count. Both outputs below are 2D, even though they are rectangular. Extra rows or columns can contain only zeros. A rectangular eye array is not a square identity matrix. Review <a href="https://www.plus2net.com/python/numpy-shape.php">array shapes</a>.

In [ ]:
for rows, columns in [(3, 4), (4, 3)]:
    a = np.eye(rows, M=columns)
    print("Shape:", a.shape)
    print(a)
    assert a.shape == (rows, columns)
    assert a.sum() == 3

**Expected output**

```text
Shape: (3, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
Shape: (4, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
```

## Positive k Selects an Upper Diagonal

For a one at row r and column c, <code>c - r == k</code>. Positive k moves the diagonal above the main diagonal. This controls positions, not the value stored there.

In [ ]:
a = np.eye(4, k=2)
print(a)
rows, columns = np.nonzero(a)
print("Positions:", list(zip(rows.tolist(), columns.tolist())))
np.testing.assert_array_equal(columns - rows, [2, 2])

**Expected output**

```text
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Positions: [(0, 2), (1, 3)]
```

## Negative k Selects a Lower Diagonal

Negative k places ones below the main diagonal. For <code>k=-1</code>, each selected column is one less than its row.

In [ ]:
a = np.eye(4, k=-1)
print(a)
rows, columns = np.nonzero(a)
print("Positions:", list(zip(rows.tolist(), columns.tolist())))
np.testing.assert_array_equal(columns - rows, [-1, -1, -1])

**Expected output**

```text
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
Positions: [(1, 0), (2, 1), (3, 2)]
```

## Out-of-Range Diagonals Return Zeros

A diagonal outside the array has no selected positions, so the result is all zeros. With shape (N, M) and positive dimensions, a nonempty diagonal requires <code>-(N-1) &lt;= k &lt;= M-1</code>. Rectangular boundaries depend on both dimensions.

In [ ]:
for k in [-3, -2, 3, 4]:
    a = np.eye(3, 4, k=k, dtype=np.int32)
    print("k:", k, "number of ones:", np.count_nonzero(a))
assert not np.eye(3, 4, k=-3).any()
assert not np.eye(3, 4, k=4).any()

**Expected output**

```text
k: -3 number of ones: 0
k: -2 number of ones: 1
k: 3 number of ones: 1
k: 4 number of ones: 0
```

## Choose Integer, Float or Boolean dtype

Set dtype according to the next operation: integers for counts, floats for numerical calculations and Boolean arrays for selection masks. See <a href="https://www.plus2net.com/python/numpy-dtype.php">dtype and conversion</a>.

In [ ]:
for dtype in [np.int32, np.float64, bool]:
    a = np.eye(3, dtype=dtype)
    print("dtype:", a.dtype)
    print(a)
    assert np.count_nonzero(a) == 3

**Expected output**

```text
dtype: int32
[[1 0 0]
 [0 1 0]
 [0 0 1]]
dtype: float64
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
dtype: bool
[[ True False False]
 [False  True False]
 [False False  True]]
```

## String dtype Uses Empty Strings off the Diagonal

With dtype=str, zero-initialized entries become empty strings, while diagonal ones become the text "1". If you want the text "0" elsewhere, create a numeric array first and convert it. Text arrays are not numeric identity matrices.

In [ ]:
a = np.eye(4, dtype=str)
b = np.eye(4, dtype=np.int32).astype(str)
print("Direct string dtype:")
print(a)
print("Numeric then converted:")
print(b)
assert a[0, 1] == '' and b[0, 1] == '0' 

**Expected output**

```text
Direct string dtype:
[['1' '' '' '']
 ['' '1' '' '']
 ['' '' '1' '']
 ['' '' '' '1']]
Numeric then converted:
[['1' '0' '0' '0']
 ['0' '1' '0' '0']
 ['0' '0' '1' '0']
 ['0' '0' '0' '1']]
```

## C and Fortran Order Change Storage, Not Values

C order stores a contiguous array by rows; F order stores it by columns. Neither option transposes the matrix or changes the diagonal. Choose storage order when an interfacing library requires it.

In [ ]:
c = np.eye(3, 4, order='C')
f = np.eye(3, 4, order='F')
print("C array: C contiguous / F contiguous:", c.flags.c_contiguous, c.flags.f_contiguous)
print("F array: C contiguous / F contiguous:", f.flags.c_contiguous, f.flags.f_contiguous)
np.testing.assert_array_equal(c, f)
assert c.flags.c_contiguous and f.flags.f_contiguous

**Expected output**

```text
C array: C contiguous / F contiguous: True False
F array: C contiguous / F contiguous: False True
```

## eye versus identity and diag

Use eye for rectangles or shifted diagonals. identity creates a square main-diagonal identity matrix. diag creates a diagonal matrix from supplied values, or extracts a diagonal from a 2D array.

In [ ]:
print("identity:")
print(np.identity(3, dtype=np.int32))
print("Custom diagonal:")
print(np.diag([2, 4, 6]))
np.testing.assert_array_equal(np.eye(3), np.identity(3))
np.testing.assert_array_equal(np.diag(np.diag([2, 4, 6])), [2, 4, 6])

**Expected output**

```text
identity:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Custom diagonal:
[[2 0 0]
 [0 4 0]
 [0 0 6]]
```

## Identity Preserves Values under Matrix Multiplication

For A shaped (2, 3), a (3, 3) identity belongs on the right and a (2, 2) identity on the left. Use <code>@</code> for matrix multiplication. Elementwise <code>*</code> is a different operation. See <a href="https://www.plus2net.com/python/numpy-broadcasting.php">broadcasting</a> for elementwise shape rules.

In [ ]:
a = np.array([[2, 4, 6], [1, 3, 5]])
right = a @ np.eye(3, dtype=np.int32)
left = np.eye(2, dtype=np.int32) @ a
print("Right identity:")
print(right)
print("Left identity:")
print(left)
np.testing.assert_array_equal(right, a)
np.testing.assert_array_equal(left, a)

**Expected output**

```text
Right identity:
[[2 4 6]
 [1 3 5]]
Left identity:
[[2 4 6]
 [1 3 5]]
```

## Use a Boolean Eye as a Diagonal Mask

This synthetic table records product comparisons. Select diagonal entries with a Boolean mask, then make a separate array in which self-comparisons are hidden. Indexing returns a 1D selection here; <code>np.where()</code> retains the original shape.

In [ ]:
comparisons = np.array([[1.0, 0.2, 0.4], [0.2, 1.0, 0.6], [0.4, 0.6, 1.0]])
mask = np.eye(3, dtype=bool)
print("Self comparisons:", comparisons[mask])
without_self = np.where(mask, np.nan, comparisons)
print("Off-diagonal report:")
print(without_self)
assert np.isnan(without_self.diagonal()).all()
np.testing.assert_array_equal(comparisons[mask], [1, 1, 1])

**Expected output**

```text
Self comparisons: [1. 1. 1.]
Off-diagonal report:
[[nan 0.2 0.4]
 [0.2 nan 0.6]
 [0.4 0.6 nan]]
```

## Combine Shifted Diagonals into a Band Matrix

A simple synthetic chain model connects each position to its immediate neighbours. Combine the main and adjacent diagonals to make a tridiagonal matrix. Dense eye arrays allocate every element; large sparse problems need a sparse representation instead.

In [ ]:
n = 4
band = 2 * np.eye(n, dtype=np.int32) - np.eye(n, k=1, dtype=np.int32) - np.eye(n, k=-1, dtype=np.int32)
print(band)
np.testing.assert_array_equal(band.diagonal(), [2, 2, 2, 2])
np.testing.assert_array_equal(band.diagonal(1), [-1, -1, -1])
assert np.array_equal(band, band.T)

**Expected output**

```text
[[ 2 -1  0  0]
 [-1  2 -1  0]
 [ 0 -1  2 -1]
 [ 0  0 -1  2]]
```

## Add a Diagonal Adjustment without Changing Other Entries

This synthetic example adds 0.5 to each diagonal entry of a square matrix. Such a construction appears in regularized linear systems, but the correct adjustment depends on the mathematical model. Match the identity size to the square input.

In [ ]:
a = np.array([[4.0, 1.0], [1.0, 3.0]])
adjustment = 0.5
changed = a + adjustment * np.eye(a.shape[0])
print(changed)
np.testing.assert_allclose(changed.diagonal(), [4.5, 3.5])
assert changed[0, 1] == a[0, 1]
assert changed[1, 0] == a[1, 0]

**Expected output**

```text
[[4.5 1. ]
 [1.  3.5]]
```

## Zero Dimensions and Invalid Sizes

A zero row or column count creates an empty 2D array. Negative dimensions and non-integer sizes are invalid. For user-supplied sizes, validate dimensions and a memory budget before allocation.

In [ ]:
for shape in [(0, 3), (3, 0)]:
    a = np.eye(*shape)
    print("Shape:", a.shape, "Size:", a.size)
    assert a.ndim == 2 and a.size == 0
for size in [-1, 2.5]:
    try:
        np.eye(size)
    except (ValueError, TypeError) as error:
        print("Rejected:", size, type(error).__name__)
    else:
        raise AssertionError("Expected an invalid size")

**Expected output**

```text
Shape: (0, 3) Size: 0
Shape: (3, 0) Size: 0
Rejected: -1 ValueError
Rejected: 2.5 TypeError
```

## device and like: Advanced Interoperability Options

NumPy 2.0 added the keyword-only device option. For NumPy eye, the permitted explicit device is <code>"cpu"</code>. The like option supports dispatch to compatible array implementations; it does not copy the reference array values or automatically inherit its dtype. Most tutorial examples need neither option.

## Common eye Mistakes

Check <code>N</code> and <code>M</code> when a result has the wrong shape. Check the sign of <code>k</code> when the diagonal is on the wrong side. Use a numeric dtype for arithmetic and bool for masks. A rectangular eye is not a square identity; C/F order does not transpose it. For large dimensions, estimate dense storage as rows times columns times itemsize. Continue with <a href="https://www.plus2net.com/python/numpy-ones.php">ones()</a>, <a href="https://www.plus2net.com/python/numpy-arange.php">arange()</a>, <a href="https://www.plus2net.com/python/numpy-linspace.php">linspace()</a> and <a href="https://www.plus2net.com/python/numpy-bincount.php">bincount()</a>.

## Exercise: Select the Upper Diagonal of a Rectangular Table

Create a Boolean mask of shape (4, 5) with k=1. Apply it to the values 0 through 19 arranged in four rows. Predict selected values 1, 7, 13 and 19, and their total 40. Use <a href="https://www.plus2net.com/python/numpy-agg-sum.php">sum()</a> to check the total.

## Exercise Solution

The selected positions are (0, 1), (1, 2), (2, 3) and (3, 4). Boolean selection follows row order for this 2D mask.

In [ ]:
data = np.arange(20).reshape(4, 5)
mask = np.eye(4, 5, k=1, dtype=bool)
selected = data[mask]
print("Mask:")
print(mask)
print("Selected:", selected)
print("Total:", selected.sum())
np.testing.assert_array_equal(selected, [1, 7, 13, 19])
assert selected.sum() == 40

**Expected output**

```text
Mask:
[[False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]
Selected: [ 1  7 13 19]
Total: 40
```

## Practice in Google Colab

<a class="btn btn-outline-primary" href="https://colab.research.google.com/github/plus2net/numpy/blob/main/numpy_eye_practice.ipynb" target="_blank" rel="noopener">Open in Google Colab</a> <a class="btn btn-outline-secondary" href="https://github.com/plus2net/numpy/blob/main/numpy_eye_practice.ipynb" target="_blank" rel="noopener">View on GitHub</a><br>All sample data is embedded. Run the examples and practise creating diagonals and applying Boolean masks. Save a copy in Drive to keep your changes.