<a href="https://colab.research.google.com/github/plus2net/numpy/blob/main/numpy_17_ufuncs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://www.plus2net.com/images/top2.jpg)        Read more on [ufuncs  ](https://www.plus2net.com/python/numpy-ufuncs.php) | [ Numpy ](https://www.plus2net.com/python/numpy.php)

In [3]:
import numpy as np

x = np.array([1., 4., 9.])
print(np.sqrt(x))              # elementwise sqrt; <class 'numpy.ufunc'>

a = np.array([1,2,3], dtype=np.float64)
b = np.array([10,20,30], dtype=np.float64)
np.add(a, b)            # same as a + b (binary ufunc)

[1. 2. 3.]


array([11., 22., 33.])

In [5]:
M = np.array([[1,2,3],[4,5,6]], dtype=np.float64)  # (2,3)
v = np.array([10,20,30], dtype=np.float64)          # (3,)
print(np.add(M, v))       # v broadcasts across rows
print(np.multiply(M, 2))  # scalar broadcast

[[11. 22. 33.]
 [14. 25. 36.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]


In [9]:
x = np.array([1,2,3,4], dtype=np.int64)

print(np.add.reduce(x))         # 10
print(np.multiply.reduce(x))    # 24

print(np.add.accumulate(x))     # [1, 3, 6, 10]
np.multiply.accumulate(x)# [1, 2, 6, 24]

np.multiply.outer([1,2,3],[10,20])  # 3x2 table

10
24
[ 1  3  6 10]


array([[10, 20],
       [20, 40],
       [30, 60]])

In [10]:
x = np.array([-1., 0., 4., 9.])
root = np.empty_like(x)

np.sqrt(x, where=(x >= 0), out=root)   # masked compute
# root: [0., 0., 2., 3.]

y = np.array([1., 2., 3., 4.])
np.add(y, 5., out=y)                   # in-place style update

array([6., 7., 8., 9.])

In [11]:
a = np.array([1, 2, 3], dtype=np.int16)
b = np.array([1.5, 2.5, 3.5], dtype=np.float32)
c = np.add(a, b)     # upcasts to float32
c.dtype

d = np.empty_like(b, dtype=np.float64)
np.add(a, b, out=d)  # control result dtype

array([2.5, 4.5, 6.5])

In [12]:
import numpy as np

def hypotenuse(a, b):          # pure Python
    return (a*a + b*b) ** 0.5

hypot_ufunc = np.frompyfunc(hypotenuse, 2, 1)

a = np.array([3, 5, 8])
b = np.array([4,12,15])
r = hypot_ufunc(a, b)          # dtype=object
r = r.astype(np.float64)       # cast if numeric needed

In [13]:
f  = lambda x: x**2 + 1
vf = np.vectorize(f)            # convenience wrapper
uf = np.frompyfunc(f, 1, 1)

x = np.arange(5)
vf(x), uf(x)   # similar API; uf returns object dtype

(array([ 1,  2,  5, 10, 17]), array([1, 2, 5, 10, 17], dtype=object))

In [14]:
# Jupyter sketch (use %timeit)
x = np.random.rand(1_000_000).astype(np.float32)
# %timeit np.add(np.multiply(x, x), 1, out=np.empty_like(x))