<a href="https://colab.research.google.com/github/plus2net/numpy/blob/main/numpy_2_shape_errors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://www.plus2net.com/images/top2.jpg)        Read more on [Shape errors ](https://www.plus2net.com/python/numpy-shape-errors.php) | [ Numpy ](https://www.plus2net.com/python/numpy.php)

In [ ]:
import numpy as np
a = np.arange(10)        # 10 elements
# print(a)
# a.reshape(3, 4)        # ValueError: 3*4=12 != 10

print(a.reshape(2, 5).shape)   # (2, 5)
print(a.reshape(-1, 5).shape)  # (2, 5)  (-1 lets NumPy infer)

[0 1 2 3 4 5 6 7 8 9]
(2, 5)
(2, 5)


In [ ]:
A = np.zeros((3,4))
b = np.array([10,20,30])       # (3,)
# A + b  # -> ValueError (align right: 4 vs 3)

b_col = b[:, None]             # (3,1) -> expands across columns
print((A + b_col).shape)       # (3,4)

(3, 4)


In [ ]:
X = np.arange(12, dtype=float).reshape(3,4)  # (rows, cols)
mu = X.mean(axis=0)                          # (4,)
print((X - mu).shape)                        # (3,4)
mu2 = X.mean(axis=1, keepdims=True)          # (3,1)
print((X - mu2).shape)                       # (3,4) column-wise broadcast

(3, 4)
(3, 4)


In [ ]:
a = np.ones((2,3))
b = np.zeros((2,3))

print(np.concatenate([a,b], axis=0).shape)  # (4,3)
print(np.concatenate([a,b], axis=1).shape)  # (2,6)

print(np.stack([a,b], axis=0).shape)        # (2,2,3) new axis at 0
print(np.stack([a,b], axis=1).shape)        # (2,2,3) -> different layout

(4, 3)
(2, 6)
(2, 2, 3)
(2, 2, 3)


In [ ]:
A = np.arange(6).reshape(2,3)   # (2,3)
B = np.arange(9).reshape(3,3)   # (3,3)
print((A @ B).shape)            # (2,3)

# (2,3) @ (2,) -> error; fix by making (3,)
v = np.array([1,2,3])
print((A @ v).shape)            # (2,)

(2, 3)
(2,)


In [ ]:
y = np.arange(6).reshape(6,1)   # (6,1)
y_flat = np.squeeze(y)          # (6,)

x = np.arange(6)                # (6,)
x_col = x[:, None]              # (6,1) using newaxis
x_row = x[None, :]              # (1,6)

In [ ]:
M = np.arange(12).reshape(3,4)
MT = M.T            # (4,3)
print(M.shape, MT.shape)
# If you need contiguous memory:
MTc = np.ascontiguousarray(MT)

(3, 4) (4, 3)


In [ ]:
T = np.arange(2*3*4).reshape(2,3,4)  # (depth, rows, cols)
bias = np.array([1,2,3,4])           # (4,)
print((T + bias).shape)              # (2,3,4)

depth_bias = np.array([10, 20])[:, None, None]  # (2,1,1)
print((T + depth_bias).shape)                    # (2,3,4)

(2, 3, 4)
(2, 3, 4)


In [ ]:
import numpy as np

# 1) Fix the broadcast to add [1,2,3] to each row of a (5,3) matrix.
A = np.arange(15).reshape(5,3)
row = np.array([1,2,3])            # (3,)
print(A + row)                      # should work

# 2) Concatenate three (10,4) blocks vertically, then compute column means.
blocks = [np.full((10,4), i) for i in range(3)]
big = np.concatenate(blocks, axis=0)   # (30,4)
print(big.mean(axis=0))

# 3) Make a column vector from [10,20,30] and add to a (3,5) array.
col = np.array([10,20,30])[:, None]    # (3,1)
B = np.arange(15).reshape(3,5)
print(B + col)

# 4) Turn a flat array of 24 items into a (2,3,4) tensor and subtract a (4,) bias.
t = np.arange(24)
T = t.reshape(2,3,4)
bias = np.array([1,2,3,4])
print(T - bias)

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]
 [13 15 17]]
[1. 1. 1. 1.]
[[10 11 12 13 14]
 [25 26 27 28 29]
 [40 41 42 43 44]]
[[[-1 -1 -1 -1]
  [ 3  3  3  3]
  [ 7  7  7  7]]

 [[11 11 11 11]
  [15 15 15 15]
  [19 19 19 19]]]
