<a href="https://colab.research.google.com/github/plus2net/numpy/blob/main/numpy_4_indexing_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://www.plus2net.com/images/top2.jpg)        Read more on [Indexing and Slicing  ](https://www.plus2net.com/python/numpy-indexing-slicing.php) | [ Numpy ](https://www.plus2net.com/python/numpy.php)

In [1]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
print(a[0])        # 10 (first element)
print(a[-1])       # 50 (last element)

# slice: start:stop (stop is exclusive)
print(a[1:4])      # [20 30 40]
print(a[:3])       # [10 20 30]
print(a[3:])       # [40 50]

# step / stride
print(a[::2])      # [10 30 50]
print(a[::-1])     # [50 40 30 20 10]  (reverse)

10
50
[20 30 40]
[10 20 30]
[40 50]
[10 30 50]
[50 40 30 20 10]


In [2]:
b = np.array([[ 1,  2,  3],
              [10, 20, 30],
              [40, 50, 60]])

print(b[0, 1])     # 2  (row 0, col 1)
print(b[1])        # [10 20 30] (row 1)
print(b[:, 0])     # [ 1 10 40] (first column)

# Sub-matrix: rows 0..1, cols 1..2
print(b[0:2, 1:3]) # [[ 2  3],
                   #  [20 30]]

# Every row, every other col
print(b[:, ::2])   # [[ 1  3],
                   #  [10 30],
                   #  [40 60]]

2
[10 20 30]
[ 1 10 40]
[[ 2  3]
 [20 30]]
[[ 1  3]
 [10 30]
 [40 60]]


In [3]:
c = np.arange(2*3*4).reshape(2,3,4)  # shape (depth=2, rows=3, cols=4)
# Pick depth=1, rows 0..1, cols 2..3
print(c[1, 0:2, 2:4])
# Ellipsis to keep all middle dims:
print(c[..., 0])   # first column from each 2D slice

[[14 15]
 [18 19]]
[[ 0  4  8]
 [12 16 20]]


In [4]:
a = np.array([0, 1, 2, 3, 4, 5])
s = a[1:4]     # slice -> view (shares memory)
s[0] = 99
print(a)       # [ 0 99  2  3  4  5]  (a changed!)

# Force a copy if you need independence:
s_copy = a[1:4].copy()
s_copy[0] = -1
print(a[1:4])  # original remains unchanged now

[ 0 99  2  3  4  5]
[99  2  3]


In [6]:
x = np.array([5, 12, 7, 22, 3, 18])
mask = x >= 10
print(mask)         # [False  True False  True False  True]
print(x[mask])      # [12 22 18]

# Conditional replace: values < 10 become 0
y = np.where(x < 10, 0, x)
print(y)            # [ 0 12  0 22  0 18]

[False  True False  True False  True]
[12 22 18]
[ 0 12  0 22  0 18]


In [8]:
# 1) Extract every 3rd element from 0..29 starting at 2
a = np.arange(30)
print(a[2::3])

# 2) From a 6x6 array, get the 3x3 center block
b = np.arange(36).reshape(6,6)
print(b[1:4, 1:4])

# 3) Replace all odd numbers in 0..19 with -1 using boolean mask
c = np.arange(20)
c[c % 2 == 1] = -1
print(c)

[ 2  5  8 11 14 17 20 23 26 29]
[[ 7  8  9]
 [13 14 15]
 [19 20 21]]
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]
