<a href="https://colab.research.google.com/github/plus2net/numpy/blob/main/numpy_11_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://www.plus2net.com/images/top2.jpg)        Read more on [Linear Algebra ](https://www.plus2net.com/python/numpy-linear-algebra.php) | [ Numpy ](https://www.plus2net.com/python/numpy.php)

In [1]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])    # shape (2,2)
B = np.array([[5, 6],
              [7, 8]])    # shape (2,2)
x = np.array([10, 20])     # shape (2,)

# Matrix @ Matrix
print(A @ B)          # [[19 22],
                      #  [43 50]]

# Matrix @ Vector
print(A @ x)          # [ 50 110]

# dot with 1-D => inner product
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
print(np.dot(u, v))   # 32

# Batched matmul (3 matrices of 2x2 each)
stack = np.stack([A, B, np.eye(2)])
vecs  = np.array([[1,1],[2,0],[0,3]])     # (3,2)
print(stack @ vecs[..., None])            # (3,2,1)

[[19 22]
 [43 50]]
[ 50 110]
32
[[[ 3.]
  [ 7.]]

 [[10.]
  [14.]]

 [[ 0.]
  [ 3.]]]


In [2]:
A = np.array([[3., 1.],
              [1., 2.]])
b = np.array([9., 8.])

x = np.linalg.solve(A, b)   # exact solution
print(x)                    # [2. 3.]

# Multiple RHS
B = np.array([[9., 1.],
              [8., 0.]])   # two RHS columns
X = np.linalg.solve(A, B)
print(X)                    # columns are solutions for each RHS

[2. 3.]
[[ 2.   0.4]
 [ 3.  -0.2]]


In [3]:
# General matrix
G = np.array([[0., -1.],
              [1.,  0.]])
vals, vecs = np.linalg.eig(G)
print(vals)        # complex eigenvalues
print(vecs)        # columns are eigenvectors

# Symmetric matrix -> use eigh
S = np.array([[2., 1.],
              [1., 2.]])
w, v = np.linalg.eigh(S)
print(w)           # sorted ascending
print(v)           # orthonormal eigenvectors (columns)
# Check: S v = v diag(w)
print(np.allclose(S @ v, v * w))

[0.+1.j 0.-1.j]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]
[1. 3.]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
True


In [4]:
M = np.array([[1., 2.],
              [3., 4.]])

# Vector norms
x = np.array([3., 4.])
print(np.linalg.norm(x, ord=2))     # 5.0

# Matrix norms
print(np.linalg.norm(M, ord=2))     # spectral norm
print(np.linalg.cond(M))            # condition number

5.0
5.464985704219043
14.933034373659268


In [5]:
A = np.array([[1., 1.],
              [1., 2.],
              [1., 3.]])  # (3,2)
b = np.array([1., 2., 2.5])

x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)
print(x)            # best-fit slope & intercept (order depends on columns)

[0.33333333 0.75      ]


In [6]:
A = np.array([[2., 1.],
              [5., 3.]])
print(np.linalg.det(A))
print(np.linalg.inv(A))     # use solve instead for systems
print(np.linalg.pinv(A))    # Moore-Penrose pseudo-inverse (SVD-based)

1.0000000000000009
[[ 3. -1.]
 [-5.  2.]]
[[ 3. -1.]
 [-5.  2.]]


In [7]:
# 1) Verify Ax = b using solve
A = np.array([[4., 1.],
              [2., 3.]])
b = np.array([9., 13.])
x = np.linalg.solve(A, b)
print(np.allclose(A @ x, b))

# 2) Show why inverse is not recommended
x_slow = np.linalg.inv(A) @ b
print(np.allclose(x, x_slow))

# 3) Use eigh for a symmetric matrix and verify orthonormality of eigenvectors
S = np.array([[3., 2.],
              [2., 3.]])
w, v = np.linalg.eigh(S)
print(np.allclose(v.T @ v, np.eye(2)))

# 4) Fit a line y = a + b x via least squares
X = np.c_[np.ones(5), np.arange(5)]
y = np.array([1., 2., 1.5, 3., 2.5])
params, *_ = np.linalg.lstsq(X, y, rcond=None)
print(params)

# 5) Compute condition numbers for two matrices; compare stability
M1 = np.array([[1., 0.], [0., 1.]])
M2 = np.array([[1., 1.], [1., 1.0001]])
print(np.linalg.cond(M1), np.linalg.cond(M2))

True
True
True
[1.2 0.4]
1.0 40002.00007491187
