<a href="https://colab.research.google.com/github/plus2net/numpy/blob/main/numpy_6_broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://www.plus2net.com/images/top2.jpg)        Read more on [Broadcasting  ](https://www.plus2net.com/python/numpy-broadcasting.php) | [ Numpy ](https://www.plus2net.com/python/numpy.php)

In [1]:
# Example A: (3, 4) +/- (4,)  -> OK
# Align from right:   (3, 4)
#                     (   4)   <-- 1D treated as (1,4), row-wise
# Result: (3,4)

# Example B: (3, 1) + (1, 4) -> OK
# Align:        (3, 1)
#               (1, 4)
# Result: (3,4)  (each 1 expands)

# Example C: (2, 3) + (2,) -> FAIL
# Align:       (2, 3)
#              (   2)
# 3 != 2 and neither is 1  -> ValueError

In [2]:
import numpy as np

A = np.arange(12).reshape(3,4)
row = np.array([10, 20, 30, 40])         # shape (4,)
col = np.array([[100],[200],[300]])      # shape (3,1)

print(A + row)  # adds to each row
print(A + col)  # adds to each column group

[[10 21 32 43]
 [14 25 36 47]
 [18 29 40 51]]
[[100 101 102 103]
 [204 205 206 207]
 [308 309 310 311]]


In [4]:
v = np.array([1, 2, 3, 4])   # shape (4,)

row_v = v[np.newaxis, :]     # (1,4)  row vector
col_v = v[:, np.newaxis]     # (4,1)  column vector

M = np.arange(8).reshape(2,4)

print(M + row_v)             # OK: (2,4) + (1,4) -> (2,4)
print(M + col_v)             # ValueError: (2,4) + (4,1)  -- incompatible
# To add col-wise properly:
print(M + col_v[:2])         # (2,4) + (2,1) -> (2,4)

[[ 1  3  5  7]
 [ 5  7  9 11]]
[[1 2 3 4]
 [6 7 8 9]]


In [7]:
T = np.arange(2*3*4).reshape(2,3,4)  # (depth=2, rows=3, cols=4)
bias_row = np.array([1,2,3,4])       # (4,)
bias_depth = np.array([100, 200])    # (2,)

print(T + bias_row)                  # (2,3,4) + (4,)    -> (2,3,4)
print(T + bias_depth[:, None, None]) # (2,3,4) + (2,1,1) -> (2,3,4)

[[[ 1  3  5  7]
  [ 5  7  9 11]
  [ 9 11 13 15]]

 [[13 15 17 19]
  [17 19 21 23]
  [21 23 25 27]]]
[[[100 101 102 103]
  [104 105 106 107]
  [108 109 110 111]]

 [[212 213 214 215]
  [216 217 218 219]
  [220 221 222 223]]]


In [8]:
# Standardize columns: (N, D) array -> subtract column means, divide by std
X = np.array([[1.0, 2.0, 3.0],
              [2.0, 3.0, 4.0],
              [3.0, 4.0, 5.0]])
mu = X.mean(axis=0)           # (D,)
sigma = X.std(axis=0)         # (D,)
Xz = (X - mu) / sigma         # (N,D) - (D,) -> (N,D)

# Distance matrix between two sets: (N, d) and (M, d)
A = np.array([[0,0],[1,1],[2,2]])       # (3,2)
B = np.array([[0,1],[1,2]])             # (2,2)
diff = A[:, None, :] - B[None, :, :]    # (3,1,2) - (1,2,2) -> (3,2,2)
D = np.sqrt((diff**2).sum(axis=-1))     # (3,2)

In [9]:
a = np.arange(6).reshape(2,3)   # (2,3)
b = np.array([10,20])           # (2,)
# a + b -> ValueError (because 3 != 2, neither is 1)

# Fix 1: treat b as column vector (2,1)
b_col = b[:, None]
print(a + b_col)                # (2,3) + (2,1) -> (2,3)

# Fix 2: repeat/expand if truly needed (use with care)
b_tiled = np.tile(b[:, None], (1, 3))  # explicit (2,3)
print(a + b_tiled)

[[10 11 12]
 [23 24 25]]
[[10 11 12]
 [23 24 25]]


In [10]:
# 1) Add a column bias [100, 200, 300] to a (3,4) matrix using broadcasting
M = np.arange(12).reshape(3,4)
bias = np.array([100, 200, 300])[:, None]
print(M + bias)

# 2) Scale each column of (5,3) by [1.0, 0.5, 2.0] without loops
X = np.arange(15).reshape(5,3)
scale = np.array([1.0, 0.5, 2.0])
print(X * scale)

# 3) Given (2,3,4) tensor T, add depth-wise bias [10, 20] correctly
T = np.arange(24).reshape(2,3,4)
depth_bias = np.array([10, 20])[:, None, None]
print(T + depth_bias)

[[100 101 102 103]
 [204 205 206 207]
 [308 309 310 311]]
[[ 0.   0.5  4. ]
 [ 3.   2.  10. ]
 [ 6.   3.5 16. ]
 [ 9.   5.  22. ]
 [12.   6.5 28. ]]
[[[10 11 12 13]
  [14 15 16 17]
  [18 19 20 21]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]]]
