<a href="https://colab.research.google.com/github/plus2net/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://www.plus2net.com/images/top2.jpg)        Read more on [Numpy ](https://www.plus2net.com/python/numpy.php) | [ Numpy ](https://www.plus2net.com/python/numpy.php)

In [11]:
import numpy as np
print(np.array([1, 2, 3]) * 10) # Output [10 20 30]

[10 20 30]


In [12]:
my_list=[1,2,3,4]
my_ar=np.array(my_list)
print(my_ar)

[1 2 3 4]


Create one 1D array from a list.

In [13]:
my_list=[[1,2,3,4],[5,6,7,8]]
my_ar=np.array(my_list)
print(my_ar)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
my_ar=np.arange(10)
print(my_ar)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
my_ar=np.arange(5,45,5)
print(my_ar)

[ 5 10 15 20 25 30 35 40]


In [19]:
my_ar=np.arange(12)
print(my_ar)
my_ar2=my_ar.reshape(3,4)
print(my_ar2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
print(my_ar2.shape)
print(my_ar2.sum())
print(my_ar2.sum(axis=0))
print(my_ar2.sum(axis=1))


(3, 4)
66
[12 15 18 21]
[ 6 22 38]


In [26]:
print(my_ar2.mean())
print(my_ar2.mean(axis=0))
print(my_ar2.mean(axis=1))

5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]
